backend:
    name: github
    repo: denisso/next-minimal-setup
    branch: main
media_folder: "public/img"
public_folder: "/img"
collections:
  - name: "pages"
    label: "Pages"
    files:
        - label: "Home"
          name: "home"
          file: "content/home.md"
          fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Photo", name: "photo", widget: "image" }
              - { label: "Birthday", name: "birthday", widget: "date" }
              - { label: "Body", name: "body", widget: "markdown" }
              - label: "Jobs"
                name: "jobs"
                widget: "list"
                fields:
                    - { label: "Company", name: "company", widget: "string" }
                    - {
                          label: "Date From",
                          name: "dateFrom",
                          widget: "date",
                      }
                    - { label: "Date To", name: "dateTo", widget: "date" }
                    - {
                          label: "Description",
                          name: "description",
                          widget: "string",
                      }
                    - {
                          label: "Responsibilities",
                          name: "responsibilities",
                          widget: "text",
                      }
  - name: posts
    label: Post
    editor:
      preview: true
    folder: content/posts
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: Title, name: title, widget: string}
      - label: 'Status'
        name: 'status'
        widget: 'select'
        options: ["Published", "Featured", "Draft"]
        default: 'Published'
      - {label: Date / Order, name: date, widget: date}
      - {label: Post Featured Image, name: postFeaturedImage, widget: image, required: false}
      - {label: Excerpt, name: excerpt, widget: text}
      - {label: Content, name: body, widget: markdown}
      - label: "Categories"
        name: "categories"
        widget: "list"
        required: false
        fields:
          - label: "Category"
            name: "category"
            widget: "relation"
            collection: "postCategories"
            searchFields: ["title"]
            valueField: "title"
      - label: "Meta"
        required: false
        name: "meta"
        widget: "object"
        fields:
          - {label: Title, name: title, widget: string, required: false}
          - {label: Description, name: description, widget: text, required: false, pattern: [".{,300}", "Must not exceed 300 characters"]}
          - {label: Canonical Link, name: canonicalLink, widget: string, required: false}
          - {label: Noindex, name: noindex, widget: boolean, required: false}
