backend:
    name: github
    repo: denisso/next-minimal-setup
    branch: main
media_folder: "public/img"
public_folder: "/img"
collections:
    - name: "pages"
      label: "Pages"
      files:
          - label: "Home"
            name: "home"
            file: "content/home.md"
            fields:
                - { label: "Name", name: "name", widget: "string" }
                - { label: "Photo", name: "photo", widget: "image" }
                - { label: "Birthday", name: "birthday", widget: "datetime" }
                - { label: "Body", name: "body", widget: "markdown" }
                - label: "Jobs"
                  name: "jobs"
                  widget: "list"
                  fields:
                      - { label: "Company", name: "company", widget: "string" }
                      - {
                            label: "Date From",
                            name: "dateFrom",
                            widget: "datetime",
                        }
                      - { label: "Date To", name: "dateTo", widget: "datetime" }
                      - {
                            label: "Description",
                            name: "description",
                            widget: "string",
                        }
                      - {
                            label: "Responsibilities",
                            name: "responsibilities",
                            widget: "text",
                        }
